name: SynapseTransfer
version: 1.0.0
api: 1.13.0
main: MrGenga\SynapseTransfer\SynapseTransfer
load: STARTUP
author: MrGenga
website: "https://github.com/MrGenga/SynapseTransfer"
description: "Transfer Minecraft: PE clients connected by Synapse to another server"
commands:
 transfer:
  permission: synapsetransfer.command.transfer
  usage: "/transfer [player] <server>"
permissions:
 synapsetransfer.command.transfer:
  description: "Allows to transfer players to another server"
  default: op
